Há!
Hnatekmar/GeneticAlgorithm pull request #15
Opened 2017-06-07 18:26 UTC by kysel

2017-06-07 18:35 UTC, kysel commented
@Hnatekmar by to mohl konečně fixnout

2017-06-07 18:36 UTC, kysel commented
Lul mail alešovi

2017-06-07 19:34 UTC, axeII requested changes
This doesn't seem right.

2017-06-07 19:44 UTC, closed without merging

2017-06-08 16:12 UTC, kysel commented
wtf